---

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install group packages
  dnf: name={{item}} state=installed
  with_items:
  - "@development tools"
  - "@fedora-packager"
  - "@virtualization"

- name: Install extra packages
  dnf: name={{ item }} state=installed
  with_items:
  - acpi
  - aide
  - android-tools
  - ansible-lint
  - appliance-tools
  - arpwatch
  - asciidoc
  - asciidoc-doc
  - aspell
  - aspell-en
  - atomic
  - autoconf
  - autofs
  - automake
  - awscli
  - binwalk
  - bpython
  - cmake
  - collectl
  - conntrack-tools
  - crypto-utils
  - dcfldd
  - ditaa
  - dnf-plugins-extras-common
  - docker
  - docker-vim
  - doge
  - doxygen
  - dstat
  - duplicity
  - elixir
  - euca2ools
  - fail2ban
  - fdupes
  - fedfind
  - fedpkg
  - feh
  - figlet
  - firewalld
  - flatpak-builder
  - fwsnort
  - fwupdate
  - gcc-c++
  - gcc-go
  - gdb-doc
  - gimp
  - gnome-tweak-tool
  - heimdall
  - hovercraft
  - htop
  - httpie
  - hub
  - imagefactory
  - imagefactory-plugins-Docker
  - imagefactory-plugins-IndirectionCloud
  - inkscape
  - inotify-tools
  - intltool
  - inxi
  - iotop
  - iptraf-ng
  - jq
  - kernel-devel
  - kismet
  - kismet-plugins
  - letsencrypt
  - lftp
  - libguestfs
  - libguestfs-tools
  - libguestfs-tools-c
  - libguestfs-xfs
  - libicns-utils
  - libmtp-examples
  - libnfs
  - libnfsidmap
  - libsemanage-devel
  - libtaskotron
  - libtool
  - libvirt
  - libvirt-python
  - libvirt-sandbox
  - livecd-tools
  - liveusb-creator
  - lm_sensors
  - lorax
  - lshw
  - lsscsi
  - ltrace
  - lynx
  - mash
  - meld
  - mysql-devel
  - ncftp
  - neovim
  - nfs-utils
  - ngrep
  - nmap
  - nmon
  - openscap
  - openscap-containers
  - openscap-daemon
  - openscap-scanner
  - openscap-utils
  - openssl-devel
  - pandoc
  - pass
  - patchutils
  - pavucontrol
  - pavumeter
  - pcp
  - pcp-doc
  - pcp-gui
  - perf
  - picocom
  - pinta
  - podman
  - policycoreutils-python
  - postfix
  - postgresql-devel
  - powertop
  - psad
  - pssh
  - pungi
  - pv
  - qiv
  - qpdf
  - ranger
  - recode
  - redis
  - rfkill
  - rpm-ostree
  - runc
  - sbcl
  - scap-workbench
  - scl-utils-build
  - screen
  - screen
  - screenfetch
  - setools-console
  - sg3_utils
  - sigul
  - smartmontools
  - socat
  - spec2scl
  - speedtest-cli
  - spin-kickstarts
  - sssd-nfs-idmap
  - strace
  - surl
  - swig
  - swig-doc
  - sysstat
  - system-storage-manager
  - task
  - tcllib
  - testcloud
  - testdisk
  - thunderbird
  - tito
  - tlp
  - tlp-rdw
  - tmux
  - tpp
  - transmission-cli
  - tuna
  - tuned
  - tuned-utils
  - tuned-utils-systemtap
  - tunir
  - units
  - vagrant
  - vagrant-doc
  - vagrant-libvirt
  - vagrant-libvirt-doc
  - valgrind
  - vim-enhanced
  - virt-top
  - whois
  - wireshark-cli
  - xbacklight
  - xclip
  - xfsdump
  - xsel
  - ykclient
  - ykpers
  - zsh

- name: Install extra fonts
  dnf: name={{ item }} state=installed
  with_items:
  - adobe-source-code-pro-fonts
  - dejavu-sans-fonts
  - dejavu-sans-mono-fonts
  - dejavu-serif-fonts
  - gnu-free-fonts-common
  - gnu-free-mono-fonts
  - gnu-free-sans-fonts
  - gnu-free-serif-fonts
  - levien-inconsolata-fonts
  - liberation-fonts-common
  - liberation-mono-fonts
  - liberation-sans-fonts
  - liberation-serif-fonts
  - mozilla-fira-mono-fonts
  - msimonson-anonymouspro-fonts
  - overpass-fonts
  - terminus-fonts
  when: install_extra_fonts

  # - name: Install cargo
  # raw: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
